### PR TITLE
fix for typo on sed ROOT

### PR DESCRIPTION
**Pull request by Bat-Shark**
Should have done a new branch but it's getting late. Easy fix??? New to github, bare with me.

### CODE REVIEW

**Comment by elmerfdz** [comment]
hmm I did merge this but might have to revert, for some reason correcting the syntax didn't work, it didn't replace ROOT with the location. Did it work for you?

**Comment by Bat-Shark** [comment]
it did in my limited testing, but I'll do some more tonight. Is is supposed to replace all instances of ROOT and DOMAIN in each line?

**Comment by elmerfdz** [comment]
I do have the correct syntax for the DOMAIN lines ([302](https://github.com/elmerfdz/OrganizrInstaller/blob/dev/centos/oci/oc_installer.sh#L302) & [304](https://github.com/elmerfdz/OrganizrInstaller/blob/dev/centos/oci/oc_installer.sh#L304) ) and it works fine but using the correct syntax for the ROOT line doesn't work ([303](https://github.com/elmerfdz/OrganizrInstaller/blob/dev/centos/oci/oc_installer.sh#L303)) , weird!

Line 303  ([302](https://github.com/elmerfdz/OrganizrInstaller/blob/dev/centos/oci/oc_installer.sh#L302) & [304](https://github.com/elmerfdz/OrganizrInstaller/blob/dev/centos/oci/oc_installer.sh#L304) ) supposed to replace ROOT with the location of organizr folder e.g /var/www/organizr.local and DOMAIN lines adds the domain name you enter to the nginx conf files and site folder.

**Comment by Bat-Shark** [comment]
Didn't realize it was passing in a var with escape characters. Turns out the correct fix is not 
`$SED -i "s/ROOT/$SITE_DIR/g" $CONFIG` 
but instead pipes
`$SED -i "s|ROOT|$SITE_DIR|g" $CONFIG`

at the symlink step, $CONFIG and $NGINX_SITES_ENABLED/$DOMAIN.conf
`/etc/nginx/sites-available/test.local.conf` `/etc/nginx/sites-enabled/test.local.conf`
is this right?

`$CURRENT_DIR = .`
`$NGINX_LOC = /etc/nginx`
`$DOMAIN = test.local`

I also get a command not found on `sudo semanage`

**Pull request merged**
