### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by Starbix**
- NGINX v1.16.0
- PHP v7.3.7
- win-acme v2.0.8

### CODE REVIEW

**Comment by elmerfdz** [comment]
Have you tested the new win-acme version by any chance?

**Comment by Starbix** [comment]
I have not. I don't have a windows machine to test it, but I thought as it's a patch/minor version it'd be safe to update. I can also open a PR to the dev branch if you want.

**Comment by elmerfdz** [comment]
yes please! I'll do a quick test once you've submitted a PR to dev

**Comment by elmerfdz** [comment]
Tried DNS validation only, which worked fine.

Thanks mate.

**Pull request merged**
